openapi: 3.0.0
info:
  title: Image Analysis API
  description: API to analyze an image and return extracted text.
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /api/v1/analysis/:
    get:
      summary: Analyze an image
      description: Accepts a URI of an image as a query parameter and returns text extracted from the image.
      parameters:
        - name: uri
          in: query
          required: true
          schema:
            type: string
          description: URL or URI pointing to the image to analyze.
      responses:
        '200':
          description: Successful analysis
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: Text extracted from the image.
        '400':
          description: Bad Request - Missing or invalid URI in query
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing URI in query"
        '500':
          description: Internal Server Error - Error during processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error in processing"
